### ISSUE TITLE
Blank responses in `abbot-cli` and the console when using a custom image

### ISSUE THREAD

**Issue by pmn** [aseriousbiz/abbot-py#154]
When using a custom image, Abbot's console and `abbot-cli` return blank responses even if the skill ran correctly. 

To replicate, set up a custom Python runner. The instructions for [setting up a runner on Fly](https://docs.ab.bot/chatops/custom-runner/fly) are good for this. 

Once the custom runner is set up, create a new Python skill. The default skill code is sufficient for testing. Try running the skill in the console, and then run in the Slack workspace. Currently, the console will return a blank response and running in Slack will return correctly: 

**console:**
<img width="681" alt="Screenshot 2023-06-08 at 11 51 27 AM" src="https://github.com/aseriousbiz/abbot-py/assets/279389/50368d4b-adc2-422e-9d07-38e240f3da44">

**Slack:**
<img width="267" alt="Screenshot 2023-06-08 at 11 51 56 AM" src="https://github.com/aseriousbiz/abbot-py/assets/279389/9b3f2153-00a3-410c-b2f2-104587023def">

**The audit log is reporting all runs successful:**
<img width="748" alt="Screenshot 2023-06-08 at 11 52 51 AM" src="https://github.com/aseriousbiz/abbot-py/assets/279389/ce22d2be-c871-4e85-8562-f2fa61ccc607">

**Comment by analogrelay** [comment]
Repro steps for local dev:

1. Launch Abbot
2. Launch the Python runner with `script/server-standalone` (this issue ONLY repros for the "standalone" hosting model)
3. Configure your Abbot with a Python Custom Runner: `http://localhost:9001/api/v1/execute` as the URL and `runnerdevsecret` as the API token
4. Run a skill that should produce a reply FROM THE CONSOLE

Expected behavior:

You should see the reply

Actual reply:

An extra blank line is returned.

---

I suspect the problem is in how the Flask-based Standalone entrypoint is emitting the response, as compared to the Azure Functions-based entrypoint used by the hosted runner.
